### ISSUE TITLE
Power

### ISSUE THREAD

**Issue by JackiePease** [zarino/netballs#1]
# Powering the ESP32

9v battery
https://docs.zerynth.com/latest/official/board.zerynth.doit_esp32/docs/index.html#power
> Power to the DOIT Esp32 DevKit v1 is supplied via the on-board USB Micro B connector or directly via the “VIN” pin. The power source is selected automatically.
> 
> The device can operate on an external supply of 6 to 20 volts. If using more than 12V, the voltage regulator may overheat and damage the device. The recommended range is 7 to 12 volts.

**Comment by JackiePease** [comment]
# Powering the SK6812 LEDs

We need 4–5 volts power supply for LEDs.
Must provide maximum of 16 amps of power (200 lights per ball, white, at full brightness).
(Based on online sources citing 58W per metre, or 2.4A for 30 LEDs).

* [GP Batteries GP410LAH 18650 Rechargeable Battery](https://cellpacksolutions.co.uk/products/batteries/gp-batteries-gp410lah-18650-rechargeable-battery/)
1.2V, so you’ll need 4 in series to get you 4.8V.
They can usually provide up to 12 amps of current draw.
With a capacity of 4.1Ah, they could give 8 amps of current for 30 minutes.
We’ll want 8 cells per ball – two 4-cell packs, providing 8A each, for a total of 16A.

* Need a battery charger: https://cellpacksolutions.co.uk/products/product-category/battery-chargers/nimh-nicd/

* Something to hold 4 in series (3d printed or bought - not a standard AA size)

* Switch to disconnect from circuit

**Comment by zarino** [comment]
John C has offered us twenty 3.7V 4000mAh Li-ion 18650 batteries.

![Wholesale-UltraFire-18650-4000mah-Li-ion-battery](https://user-images.githubusercontent.com/739624/59554468-2b429f00-8f9b-11e9-9fc4-5197eab88119.jpg)

Despite these being 3.7V (rather than 5V) we’ve had one driving a strand test on 60 SK6812 LEDs, at full brightness, and it’s been working fine for 45 minutes and counting.

**Comment by zarino** [comment]
We did this with John C’s 3.7V 4000mAh Li-ion 18650 batteries.

It wasn’t perfect though (the low voltage caused random flickering) so maybe in future we’ll want to consider proper 5V alternatives. Potentially two 3.7V 18650s, in series, with a step down converter.
