### ISSUE TITLE
3D print battery holders for inside the balls

### ISSUE THREAD

**Issue by zarino** [zarino/netballs#6]
Spun out from #1.

I think we want four of the 3.7V 4000mAh Li-ion 18650 batteries per ball. So maybe we should 3D print a 4-cell holder, rather than 4 separate ones?

Need to consider whether we want to power the ESP32s off the same 4 batteries, or off a 5th battery, or off something else entirely.

**Comment by JackiePease** [comment]
We bought standard battery holders to save time
